# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moodle_forStudent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'IQKeyboardManagerSwift'
  # Pods for Moodle_forStudent

end
